### PR TITLE
ST-202 - refactor playbook for integration

### PR DESCRIPTION
**Pull request by piersharding**
* add in playbook for running local Minikube
* runs inside and outside of Vagrant
* install minikube, helm, kubectl
* uses Calico for Pod Network
* enables Ingress

### CODE REVIEW

**Comment by piersharding** [comment]
This PR is waiting on the addition of an option to install Traefik or Nginx as the Ingress Controller

**Comment by flyingfrog81** [comment]
Trying to run it on my OSX. 
`make vagrant_install` installs the relevant plugins for disksize etc... 
`make vagrant_up` gets stuck at: 
```bash
$ make vagrant_up 
V_BOX: ubuntu/bionic64
V_DISK_SIZE: 50GB
V_MEMORY: 4096
V_CPUS: 2
V_IP: 172.200.0.25
V_BOX=ubuntu/bionic64 \
	V_DISK_SIZE=50GB \
	V_MEMORY=4096 \
	V_CPUS=2 \
	V_IP=172.200.0.25 \
		vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' version '20190205.0.0' is up to date...
==> default: Setting the name of the VM: minikube
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Resized disk: old 10240 MB, req 51200 MB, new 51200 MB
==> default: You may need to resize the filesystem from within the guest.
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.18
    default: VirtualBox Version: 6.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/m.bartolini/Projects/k8s-integration
==> default: Running provisioner: ansible_local...
    default: Installing Ansible...
```

the machine has been created and I can `vagrant ssh` into it.

**Comment by flyingfrog81** [comment]
@Matteo04052017 is right, we can NOT have different infos on different repos for the same task. So we might move all of this into the ansible-playbooks repo, or alternatively remove the minikube setup from it.

**Comment by flyingfrog81** [comment]
running `vagrant provision` on the created virtual machine results in an error downloading the docker apt key. Log attached. 
[ansible.log](https://github.com/ska-telescope/k8s-integration/files/3301150/ansible.log)

**Comment by piersharding** [comment]
> running `vagrant provision` on the created virtual machine results in an error downloading the docker apt key. Log attached.
> [ansible.log](https://github.com/ska-telescope/k8s-integration/files/3301150/ansible.log)

Is that an intermittent failure?  I can curl https://download.docker.com/linux/ubuntu/gpg .  Were you able to reach anywhere else from within the box?

**Comment by piersharding** [comment]
> Trying to run it on my OSX.
...
> the machine has been created and I can `vagrant ssh` into it.

This sounds like a networking issue - is it possible that there is some kind of clash with the Vagrantfile config.vm.network - private_netowrk setting (V_IP=172.200.0.25) ?  If you ssh into the box can you get out to anywhere with curl/wget ?

**Comment by piersharding** [comment]
> Nice work. The doubt I have is that there is a similar role in the ansible-playbook repository (https://github.com/ska-telescope/ansible-playbooks/tree/master/roles/integration/tasks) that needs to be merged with this. I would prefer to keep this repository with only charts and put all the playbooks in the other repository. Perhaps we need to talk about it if you have a different vision including Marco as well.
> Concerning vagrant, the main concern I have is that our "customer" use windows and mac...

Hi -  I wondered about this originally as I looked at ansible-playbooks first.  I would be happy to separate this out and merge with that as a strategy from here - my aim is to provide a reference deployment of k8s that can be run directly on host or in Vagrant - if we can get enough variety of test machines available then I think this should be possible for Linux, Windows and OSX.

I would like to bottom out the problems below first if possible, though.

**Comment by Matteo04052017** [comment]
Piers, I am sorry, but I don't think I have completely understood your comment/vision. 
Providing a reference deployment of k8s that can be run directly on host or in Vagrant does not include putting the work in a different repository (this one). That's my point. The ST-202 story talks about refactor what we have and not create another role in another repository.  At the moment the procedure for deploying the k8s-integration in the integration environment has not been updated yet and I would take that as priority. 
However, if there are some advantages in having the ansible procedure here and not in the other repository, we can talk about it. But I would avoid having two procedure that does the same thing in two different way.

**Comment by flyingfrog81** [comment]
> > Trying to run it on my OSX.
> > ...
> > the machine has been created and I can `vagrant ssh` into it.
> 
> This sounds like a networking issue - is it possible that there is some kind of clash with the Vagrantfile config.vm.network - private_netowrk setting (V_IP=172.200.0.25) ? If you ssh into the box can you get out to anywhere with curl/wget ?

I got it to work by setting the private ip to 172.16.0.25 . Is 172.200.X.X in the private address space ? Now proceeding with further tests

**Comment by flyingfrog81** [comment]
minor one, `make k8s` returns an error

```bash
$ make k8s
Kubernetes cluster-info:
Kubernetes master is running at https://10.0.2.15:8443
KubeDNS is running at https://10.0.2.15:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Helm version:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Error: could not find tiller
Makefile:42: recipe for target 'k8s' failed
make: *** [k8s] Error 1
```

**Comment by piersharding** [comment]
> Piers, I am sorry, but I don't think I have completely understood your comment/vision.
> Providing a reference deployment of k8s that can be run directly on host or in Vagrant does not include putting the work in a different repository (this one). That's my point. The ST-202 story talks about refactor what we have and not create another role in another repository. At the moment the procedure for deploying the k8s-integration in the integration environment has not been updated yet and I would take that as priority.
> However, if there are some advantages in having the ansible procedure here and not in the other repository, we can talk about it. But I would avoid having two procedure that does the same thing in two different way.

Hi Matteo - I think it would greatly help me if you could describe to me what you think needs to be done from here to satisfy ST-202.  I am concerned that I am missing the objectives.
Thanks,
Piers.

**Comment by piersharding** [comment]
> > > Trying to run it on my OSX.
> > > ...
> > > the machine has been created and I can `vagrant ssh` into it.
> > 
> > 
> > This sounds like a networking issue - is it possible that there is some kind of clash with the Vagrantfile config.vm.network - private_netowrk setting (V_IP=172.200.0.25) ? If you ssh into the box can you get out to anywhere with curl/wget ?
> 
> I got it to work by setting the private ip to 172.16.0.25 . Is 172.200.X.X in the private address space ? Now proceeding with further tests

Hi -
172.200.X.X is outside the private address space, but this worked on Ubuntu.  I'll do some further testing in 172.16 -> 172.31.

**Comment by piersharding** [comment]
> minor one, `make k8s` returns an error
> 
> ```
> $ make k8s
> Kubernetes cluster-info:
> Kubernetes master is running at https://10.0.2.15:8443
> KubeDNS is running at https://10.0.2.15:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
> 
> To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
> 
> kubectl version:
> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> 
> Helm version:
> Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
> Error: could not find tiller
> Makefile:42: recipe for target 'k8s' failed
> make: *** [k8s] Error 1
> ```

I'll fix this - thanks.

**Comment by Matteo04052017** [comment]
Hi Piers, I was talking about this little change: https://github.com/ska-telescope/ansible-playbooks/commit/061377c8dd86982704f77a17fa8ebc3ae5bddf50

Perhaps it would be better that I explain the TM vision on the lifecycle... Anyway, now the integration environment is back online and we can talk about this with calm.

**Comment by flyingfrog81** [comment]
Now running from top to bottom ok on my OSX using vagrant. The only ansible task that errors out is: 
```
TASK [k8s : After minikube configuration, we check minikube status] ************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "minikube status --format \"host: {{.Host}} kubelet: {{.Kubelet}} apiserver: {{.APIServer}} kubectl: {{.Kubeconfig}}\"", "delta": "0:00:00.123809", "end": "2019-06-20 12:04:41.365956", "msg": "non-zero return code", "rc": 1, "start": "2019-06-20 12:04:41.242147", "stderr": "", "stderr_lines": [], "stdout": "host:  kubelet:  apiserver:  kubectl: ", "stdout_lines": ["host:  kubelet:  apiserver:  kubectl: "]}
...ignoring
```
Attached the complte [ansible.log](https://github.com/ska-telescope/k8s-integration/files/3310292/ansible.log)

**Comment by piersharding** [comment]
> Now running from top to bottom ok on my OSX using vagrant. The only ansible task that errors out is:
> 
> ```
> TASK [k8s : After minikube configuration, we check minikube status] ************
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "minikube status --format \"host: {{.Host}} kubelet: {{.Kubelet}} apiserver: {{.APIServer}} kubectl: {{.Kubeconfig}}\"", "delta": "0:00:00.123809", "end": "2019-06-20 12:04:41.365956", "msg": "non-zero return code", "rc": 1, "start": "2019-06-20 12:04:41.242147", "stderr": "", "stderr_lines": [], "stdout": "host:  kubelet:  apiserver:  kubectl: ", "stdout_lines": ["host:  kubelet:  apiserver:  kubectl: "]}
> ...ignoring
> ```
> 
> Attached the complte [ansible.log](https://github.com/ska-telescope/k8s-integration/files/3310292/ansible.log)

Yes - that is poor error handling (ignore_errors).  I've committed a better fix.

**Comment by piersharding** [comment]
I have pulled out all of the ansible and vagrant work from here, and put it in https://github.com/ska-telescope/ansible-playbooks/pull/5.
I have retained smaller changes deploy all, certificates, and make targets

**Pull request merged**
